version: "3"

services:

  job-runner:
    build: .
    container_name: job-runner
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app

  logstash-service:

    image: docker.elastic.co/logstash/logstash:6.4.0

    command: logstash -f /etc/logstash/conf.d/logstash.conf

    volumes:
    - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro

    ports:
    - "9200:9200"

    container_name: logstash-service

    env_file:
      - ./app/.env

    volumes:
      - ./app/app.log:/app.log